spring:
  application:
    name: webapi
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

application:
  endpoint:
    search: /search
    accounts: /accounts
