spring:
  application:
    name: webapi
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${DDL_BEHAVIOUR}

application:
  endpoint:
    search: /search
    types: /types
    authentication: /registration
    accounts: /accounts
    animals: /animals
    locations: /locations
    areas: /areas
    analytics: /analytics
  init:
    accounts:
      admin:
        email: ${ADMIN_EMAIL}
        password: ${ADMIN_PASSWORD}
      chipper:
        email: ${CHIPPER_EMAIL}
        password: ${CHIPPER_PASSWORD}
      user:
        email: ${USER_EMAIL}
        password: ${USER_PASSWORD}
